from django.conf.urls import *

urlpatterns = patterns('kenyakids.web.views',
    url(r'^$', 'index', name='home'),
    url(r'^chooseproject/(?P<origin>\w+)/$', 'chooseproject', name='chooseproject'),
    url(r'^areas/$', 'areas', name='areas_list'),
    url(r'^statistics/(?P<projectid>\d+)/$', 'statistics'),
    url(r'^areafull/(?P<area_id>\d+)/$', 'areafull'),
    url(r'^children/$', 'children', name="children"),
    url(r'^childgal/$', 'childgal'),
    url(r'^childfull/(?P<child_id>\d+)/$', 'childfull', name="childfull"),
    url(r'^annualreport/(?P<child_id>\d+)/$', 'annualreport'),
    url(r'^freechildren/(?P<projectid>\d+)/$', 'freechildren', name="freechildren"),
    url(r'^freechildfull/(?P<child_id>\d+)/$', 'freechildfull', name="freechildfull"),
    url(r'^sponsors/$', 'sponsors', name="sponsors"),
    url(r'^sponsorfull/(?P<sponsor_id>\d+)/(?:(?P<projectid>\d+)/)$', 'sponsorfull', name="sponsorfull"),
    url(r'^childsearch/(?P<projectid>\d+)/(?:(?P<start_code>\w+)/(?P<end_code>\w+)/)?$', 'childsearch', name="childsearch"),
    url(r'^sponsorsearch/(?P<projectid>\d+)/(?:(?P<sstr>\w+)/)?$', 'sponsorsearch', name="sponsorsearch"),
    url(r'^printstats/$', 'printstats'),
    url(r'^download/$', 'download'),
    url(r'^bulkmail/(?P<projectid>\d+)/((?P<sstr>\w*)/)?$', 'bulkmail', name='bulkmail'),
    url(r'^mailinglist/(?P<projectid>\d+)/$', 'mailinglist'),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^translation/$', 'trans_page', name='translation'),
    url(r'^trans-db-strings/$', 'trans_db_strings', name='trans-db-strings'),
    )
